name: npm_installation
on: push
jobs:
  npm_checking:
    runs-on: ubuntu-latest
    steps:
      - name: exit code checking
        run: |
          if command -v node &> /dev/null; then
          echo $?
          fi
      - name: installation checking
        run: |
          if command -v node &> /dev/null; then
          a=$(node -v)
          echo "Node_Version=$a" >> GITHUB_ENV
          echo " The node.js installed version is $a"
          else
          echo "node.js is not installed"
          fi
  npm_install:
    needs: npm_checking
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: npm installation
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: updating npm
        run: |
          present_npm_ver=$(npm -v)
          required_npm_version=$(npm show npm version)
          if [ "$present_npm_ver"!="$required_npm_version" ]; then
          echo "updating npm to latest version..."
          npm install -g npm@$required_npm_version
          echo "the npm version is $(npm -v)"

          else
          echo "npm is at his latest version"
          fi
          

          
        
          
