name: installation
on: push
jobs: 
  npm_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checking the exitcode
        run: |
          command -v node &> /dev/null
          echo "$?"
      - name: cheking installation
        run: |
          if command -v node &> /dev/null; then
          a=$(node -v)
          echo "Node_Version=$a" >> $GITHUB_ENV
          else
          echo " nodeJs is not installed"
          fi

      - uses: actions/checkout@v4    
      - name: installing latest version
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: |
          echo "checking lock file is installed or not"
          ls -la
          #ls -la package-lock.json
          if [ -f package-lock.json ]; then
          npm ci
          else
          npm install 
          fi
      - run: npm test
          
        
          
